Faturi.WebUi/Models/ErrorViewModel.cs
namespace Faturi.WebUi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Faturi.WebUi/Controllers/BeneficiarioController.cs
using Faturi.Application.DTOs;
using Faturi.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Faturi.WebUi.Controllers
{
    public class BeneficiarioController : Controller
    {
        private readonly IConvevioService _convenioService;
        private readonly IBeneficiarioService _beneficiarioService;
        private readonly IWebHostEnvironment _environment;

        public BeneficiarioController(IBeneficiarioService beneficiarioService, IConvevioService convenioService, IWebHostEnvironment environment)
        {
            _beneficiarioService = beneficiarioService;
            _environment = environment;
            _convenioService = convenioService;

        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var beneficiarios = await _beneficiarioService.GetBeneficiarios();
            return View(beneficiarios);
        }

        [HttpGet()]
        public async Task<IActionResult> Create()
        {
            ViewBag.ConvenioId =
            new SelectList(await _convenioService.GetConvenios(), "Id", "Nome");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BeneficiarioDTO beneficiarioDTO)
        {
            if (ModelState.IsValid)
            {
                await _beneficiarioService.Add(beneficiarioDTO);
                return RedirectToAction(nameof(Index));

            }
            else
            {
                ViewBag.CategoryId =
                            new SelectList(await _convenioService.GetConvenios(), "Id", "Name");
            }
            return View(beneficiarioDTO);
        }

        [HttpGet()]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var beneficiarioDTO = await _beneficiarioService.GetById(id);

            if (beneficiarioDTO == null) return NotFound();

            var convenio = await _convenioService.GetConvenios();
            ViewBag.ConvenioId = new SelectList(convenio, "Id", "Nome", beneficiarioDTO.ConvenioId);

            return View(beneficiarioDTO);
        }

        [HttpPost()]
        public async Task<IActionResult> Edit(BeneficiarioDTO beneficiarioDTO)
        {
            if (ModelState.IsValid)
            {
                await _beneficiarioService.Update(beneficiarioDTO);
                return RedirectToAction(nameof(Index));
            }
            return View(beneficiarioDTO);
        }

        [HttpGet()]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var productDto = await _beneficiarioService.GetById(id);

            if (productDto == null) return NotFound();

            return View(productDto);
        }

        [HttpPost(), ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _beneficiarioService.Remove(id);
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var beneficiarioDto = await _beneficiarioService.GetById(id);

            if (beneficiarioDto == null) return NotFound();
            var wwwroot = _environment.WebRootPath;
            var image = Path.Combine(wwwroot, "images\\" + beneficiarioDto.Foto);
            var exists = System.IO.File.Exists(image);
            ViewBag.ImageExist = exists;

            return View(beneficiarioDto);
        }
        
    }
}

Faturi.WebUi/Controllers/ConvenioController.cs
using Faturi.Application.DTOs;
using Faturi.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Faturi.WebUi.Controllers
{
    public class ConvenioController : Controller
    {
        private readonly IConvevioService _convevioService;

        public ConvenioController(IConvevioService convevioService)
        {
            _convevioService = convevioService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var convenios = await _convevioService.GetConvenios();
            return View(convenios);
        }

        [HttpGet()]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ConvenioDTO category)
        {
            if (ModelState.IsValid)
            {
                await _convevioService.Add(category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        [HttpGet()]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var categoryDto = await _convevioService.GetById(id);
            if (categoryDto == null) return NotFound();
            return View(categoryDto);
        }

        [HttpPost()]
        public async Task<IActionResult> Edit(ConvenioDTO convenioDTO)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _convevioService.Update(convenioDTO);
                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(convenioDTO);
        }

        [HttpGet()]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var convenioDTO = await _convevioService.GetById(id);

            if (convenioDTO == null) return NotFound();

            return View(convenioDTO);
        }

        [HttpPost(), ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _convevioService.Remove(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var convenioDTO = await _convevioService.GetById(id);

            if (convenioDTO == null)
                return NotFound();

            return View(convenioDTO);
        }
    }
}

Faturi.WebUi/Controllers/HomeController.cs
using Faturi.WebUi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Faturi.WebUi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Faturi.WebUi/Views/Beneficiario/Create.cshtml
@model Faturi.Application.DTOs.BeneficiarioDTO

<h2>Register new Product</h2>

<form asp-action="Create">

    <div class="form-horizontal">

        <hr />

        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Nome" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Carteira" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Carteira" class="form-control" />
                <span asp-validation-for="Carteira" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Foto" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CPF" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CPF" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Nascimento" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <label asp-for="ConvenioId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ConvenioId" class="form-control" asp-items="ViewBag.ConvenioId"> </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

Faturi.WebUi/Views/Beneficiario/Delete.cshtml
@model Faturi.Application.DTOs.BeneficiarioDTO

<h3>Delete Product</h3>

<h4>Are you sure you want to delete this?</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Carteira)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Carteira)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Faturi.WebUi/Views/Beneficiario/Details.cshtml
@model Faturi.Application.DTOs.BeneficiarioDTO

<h3>Product Details</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Nome)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Nome)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.CPF)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.CPF)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Foto)</dt>
        <dd class="col-sm-10">
            @if (!ViewBag.ImageExist)
            {
                <img src="~/images/noimage.png" class="rounded-circle"
                 height="300" width="300" asp-append-version="true" />
            }
            else
            {
                <img src="~/images/@Model.Foto" class="rounded-circle"
                 height="300" width="300" asp-append-version="true" />
            }
        </dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Carteira)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Carteira)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Nascimento)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Nascimento)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Convenio)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Convenio.Nome)</dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Faturi.WebUi/Views/Beneficiario/Edit.cshtml
@model Faturi.Application.DTOs.BeneficiarioDTO

<h3>Edit Product</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Carteira" class="control-label"></label>
                <input asp-for="Carteira" class="form-control" />
                <span asp-validation-for="Carteira" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CPF" class="control-label"></label>
                <input asp-for="CPF" asp-format="{0:N2}" class="form-control" />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ConvenioId" class="control-label"></label>
                <select asp-for="ConvenioId" class="form-control" asp-items="ViewBag.ConvenioId"></select>
                <span asp-validation-for="ConvenioId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Faturi.WebUi/Views/Beneficiario/Index.cshtml
@model IEnumerable<Faturi.Application.DTOs.BeneficiarioDTO>

@{
    ViewData["Title"] = "Administração de Beneficiários";
}
<style>
    .modal-lg {
        max-width: 80%;
    }
</style>
<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="fas fa-plus"></span> Cadastrar Novo
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Carteira)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CPF)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Convenio)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Carteira)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CPF)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Convenio.Nome)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="fas fa-edit">Editar</span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                            <span class="fas fa-search">Detalhes</span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                            <span class="fas fa-trash-alt">Deletar</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Faturi.WebUi/Views/Convenio/Create.cshtml
@model Faturi.Application.DTOs.ConvenioDTO;

@{
    ViewData["Title"] = "Registrar Novo Convenio";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create" method="post">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="Nome" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ANS" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="ANS" class="form-control" />
                    <span asp-validation-for="ANS" class="text-danger"></span>
                </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <br />
                <input type="submit" value="Cadastrar" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Voltar a Lista</a>
            </div>
        </div>
    </div>
</form>

Faturi.WebUi/Views/Convenio/Delete.cshtml
@model Faturi.Application.DTOs.ConvenioDTO

<h3>Excluir Convenio</h3>

<h4>Você tem ecrteza que deseja excluir este convenio?</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ANS)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ANS)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-success">Voltar a lista</a>
    </form>
</div>

Faturi.WebUi/Views/Convenio/Details.cshtml
@model Faturi.Application.DTOs.ConvenioDTO

<h3>Detalhes do Convenio</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ANS)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ANS)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-success">Voltar a Lista</a>
</div>

Faturi.WebUi/Views/Convenio/Edit.cshtml
@model Faturi.Application.DTOs.ConvenioDTO

<h3>Atualiza Convenio</h3>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="ANS" class="control-label"></label>
                <input asp-for="ANS" class="form-control" />
                <span asp-validation-for="ANS" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Gravar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-success">Voltar para a lista</a>
            </div>
        </form>

    </div>
</div>
<div>
    
</div>

Faturi.WebUi/Views/Convenio/Index.cshtml
@model IEnumerable<Faturi.Application.DTOs.ConvenioDTO>

@{
    ViewData["Title"] = "Adminsitração de Convenios";
}

<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="fas fa-plus"></span> Cadastrar Novo
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ANS)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ANS)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="fas fa-edit">Editar</span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                            <span class="fas fa-search">Detalhes</span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                            <span class="fas fa-trash-alt">Deletar</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Faturi.WebUi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Faturi.WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Faturi.WebUi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Faturi.WebUi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Faturi.WebUi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Convenio" asp-action="Index">Convevios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beneficiario" asp-action="Index">Beneficiários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Faturi.WebUi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>